name: Test

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - 'packages/**/*.py'
      - 'uv.lock'
  pull_request:
    paths:
      - 'packages/**/*.py'
      - 'uv.lock'

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run pytest
        run: nix develop '.?dir=dev#ci' -c pytest
        env:
          TERM: "dumb"
