name: Test

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - 'packages/**/*.py'
      - 'uv.lock'
  pull_request:
    paths:
      - 'packages/**/*.py'
      - 'uv.lock'

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run pytest
        run: nix develop '.?dir=dev#ci' -c pytest
        env:
          TERM: "dumb"
